on:
  push:
    branches:
      - master
name: Deploy Site
jobs:
  all:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'
    - name: Install
      run: npm install
    - name: Build
      run: npm run build-styleguide
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: gauntface/styleguide.gauntface.com
        publish_branch: master
        publish_dir: ./styleguide/public